# Generated by Django 5.2 on 2025-04-20 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(blank=True, max_length=100)),
                ('email_company', models.CharField(blank=True, max_length=100)),
                ('phone_company', models.TextField(blank=True)),
                ('address_company', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='company_images/')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('surname', models.CharField(blank=True, max_length=100, null=True)),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.TextField(blank=True)),
                ('about', models.TextField(blank=True)),
                ('years', models.CharField(blank=True, max_length=100)),
                ('experience', models.CharField(blank=True, max_length=100)),
                ('admin_type', models.CharField(choices=[('super', 'Главный администратор'), ('employer', 'Работодатель'), ('none', 'Обычный пользователь')], default='none', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('JobTitle', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('graphy', models.CharField(max_length=100)),
                ('watch', models.CharField(max_length=100)),
                ('information', models.TextField(blank=True)),
                ('education_information', models.TextField(blank=True)),
                ('education_link', models.TextField(blank=True)),
                ('education', models.CharField(choices=[('1', 'Не требуется'), ('2', 'Среднее'), ('3', 'Высшее')], default='1', max_length=1)),
                ('selection', models.CharField(choices=[('1', 'Актуальные'), ('2', 'Перспективные')], default='1', max_length=1)),
                ('category', models.CharField(choices=[('1', 'Производство'), ('2', 'Финансы'), ('3', 'Образование')], default='1', max_length=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='main.company')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_vacancies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
            },
        ),
        migrations.CreateModel(
            name='VacanciesMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_applications', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='main.vacancies')),
            ],
            options={
                'unique_together': {('vacancy', 'user')},
            },
        ),
    ]
